# Generated by Django 2.2.7 on 2019-12-02 19:49

import django.contrib.auth.models
from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('tipo', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('CLIENTE', 'Cliente')], max_length=15, verbose_name='Tipo do usuário')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='Email')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Permitir acesso como gerenciador do sistema')),
                ('is_active', models.BooleanField(default=True, help_text='Liberar acesso ao sistema', verbose_name='ativo')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='slug')),
                ('clientes', models.ManyToManyField(to='cliente.Cliente')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ['nome'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('administradores_ativos', usuario.models.UsuarioAdministradoresAtivosManager()),
                ('clientes_ativos', usuario.models.UsuarioClientesAtivosManager()),
            ],
        ),
    ]
